- name: Fetching from github
  hosts: localhost
  tasks:
          - name: get inventory
            get_url:
                    dest: /home/student/mnkc/inventory
                    url: https://raw.githubusercontent.com/akhilesh-jain1729/Ansible-Internship-Project/main/inventory
                    owner: student
                    group: student
                    
          - name: get key
            get_url:
                    url: https://raw.githubusercontent.com/akhilesh-jain1729/Ansible-Internship-Project/main/k8s-cluster-vm-key.pem
                    dest: /home/student/mnkc/k8s-cluster-vm-key.pem
                    mode: 0600
                    owner: student
                    group: student
            ignore_errors: True
