apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-app-deployment
spec:
  selector:
    matchLabels:
      app: heart-app
  replicas: 2
  template:
    metadata:
      labels:
        app: heart-app
    spec:
      nodeSelector:
        aws: slave
      containers:
      - name: heart-app
        image: visheshgargavi/k8s_tens
        ports:
        - containerPort: 81
---
apiVersion: v1
kind: Service
metadata:
  name: heart-app-service
spec:
  ports:
  - port: 81
    protocol: TCP
    targetPort: 81
    nodePort: 32767
  selector:
    app: heart-app
  type: NodePort
status:
  loadBalancer: {}
